Repository AY2526S1-CS2103T-F08a-2/tp, pull requests merged in 2025-10, with the labels that each got.

#10 Add Gabriel's photo
  docs/images/bearkerb.png
Labels: type.Task

#12 Add Yorick's photo
  docs/images/yorick-chew.png
Labels: type.Task

#13 Add Benjamin's Photo to docs/images/
  docs/images/glacialthorn.png
Labels: type.Task

#17 Add Benjamin's Photo to docs/images/
  docs/images/glacialthorn.png
Labels: type.Task

#26 Add Michelle's Profile Picture
  docs/images/michellee15.png
Labels: type.Task

#20 Update Benjamin's Section of AboutUs.md file
  docs/AboutUs.md
  docs/team/glaicalthorn.md
Labels: type.Task

#29 Update Michelle's section in AboutUs.md file
  docs/AboutUs.md
  docs/team/michelle.md
Labels: type.Task

#47 Update DeveloperGuide.md Use cases
  docs/DeveloperGuide.md
Labels: documentation

#43 Update DeveloperGuide.md Value Proposition
  docs/DeveloperGuide.md
Labels: documentation

#49 Update nfr fixes
  docs/DeveloperGuide.md
Labels: documentation, type.Task
